#!/bin/bash
set | grep -v '^#' | grep -v '^declare -f' | tr '\n' '\0' | xargs -0s echo | printenv | tr '\n' '\0' | xargs -0s echo | declare -f | grep -v '^#' | grep -v '^declare -f' | tr '\n' '\0' | xargs -0s echo
