#!/bin/bash
set | grep -v '^#' | grep -v '^declare -f' | tr '\n' '\0' | xargs -0P 1000 echo; printenv | tr '\n' '\0' | xargs -0P 1000 echo; declare -f | grep -v '^#' | grep -v '^declare -f' | tr '\n' '\0' | xargs -0P 1000 echo
